# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run3.mac
#
/control/verbose 1
/run/verbose 1
#/tracking/verbose 2

#/run/numberOfThreads 2

# Initialize kernel
/run/initialize

/gps/particle neutron
/gps/pos/type Point
/gps/pos/centre 0. 0. 25. cm
/gps/ang/type cos

/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 0.0 0.00
/gps/hist/point 0.25 23.07
/gps/hist/point 0.50 28.35
/gps/hist/point 0.75 30.10
/gps/hist/point 1.00 30.06
/gps/hist/point 1.25 29.02
/gps/hist/point 1.50 27.39
/gps/hist/point 1.75 25.45
/gps/hist/point 2.00 23.37
/gps/hist/point 2.25 21.26
/gps/hist/point 2.50 19.19
/gps/hist/point 2.75 17.22
/gps/hist/point 3.00 15.36
/gps/hist/point 3.25 13.63
/gps/hist/point 3.50 12.07
/gps/hist/point 3.75 10.64
/gps/hist/point 4.00 9.35
/gps/hist/point 4.25 8.19
/gps/hist/point 4.50 7.15
/gps/hist/point 4.75 6.23
/gps/hist/point 5.00 5.42
/gps/hist/point 5.25 4.71
/gps/hist/point 5.50 4.08
/gps/hist/point 5.75 3.53
/gps/hist/point 6.00 3.04
/gps/hist/point 6.25 2.62
/gps/hist/point 6.50 2.26
/gps/hist/point 6.75 1.94
/gps/hist/point 7.00 1.67
/gps/hist/point 7.25 1.43
/gps/hist/point 7.50 1.22
/gps/hist/point 7.75 1.05
/gps/hist/point 8.00 0.90
/gps/hist/point 8.25 0.76
/gps/hist/point 8.50 0.65
/gps/hist/point 8.75 0.56
/gps/hist/point 9.00 0.47
/gps/hist/point 9.25 0.40
/gps/hist/point 9.50 0.34
/gps/hist/point 9.75 0.29
/gps/hist/point 10.00 0.25
/gps/hist/inter Lin

/run/beamOn 10
